build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.21
  amd64: ghcr.io/home-assistant/amd64-base:3.21
  armv7: ghcr.io/home-assistant/armv7-base:3.21
labels:
  org.opencontainers.image.title: DoorOpener
  org.opencontainers.image.description: >-
    Secure web interface for controlling smart door openers via Home Assistant
  org.opencontainers.image.source: https://github.com/leonardpitzu/DoorOpener
  org.opencontainers.image.licenses: MIT
