build_from:
  aarch64: ghcr.io/sloth-on-meth/dooropener:latest
  amd64: ghcr.io/sloth-on-meth/dooropener:latest
  armv7: ghcr.io/sloth-on-meth/dooropener:latest
labels:
  org.opencontainers.image.title: "DoorOpener"
  org.opencontainers.image.description: "A secure web interface for controlling smart door openers via Home Assistant."
  org.opencontainers.image.source: "https://github.com/Sloth-on-meth/DoorOpener"
