name: Docker Build and Push

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Login to GHCR only for pushes/releases; PRs (especially from forks) should not push
      - name: Log in to GitHub Container Registry (PAT)
        if: github.event_name != 'pull_request' && secrets.GHCR_PAT != ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Log in to GitHub Container Registry (GITHUB_TOKEN fallback)
        if: github.event_name != 'pull_request' && secrets.GHCR_PAT == ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: reponame
        run: |
          echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (main branch)
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ steps.reponame.outputs.repository }}:latest

      - name: Build and push Docker image (release)
        if: github.event_name == 'release'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ steps.reponame.outputs.repository }}:${{ github.event.release.tag_name }}
